[tool.poetry]
name = "xitomatl"
version = "0.1.0"
description = "Simple pomodoro timer app residing in tray"
license = "GPL-2.0-or-later"
authors = ["Lukas Holecek <hluk@email.cz>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
PySide6-Essentials = "^6.5.1"

[tool.poetry.dev-dependencies]
Nuitka = "^1.8"
zstandard = "^0.21.0"
imageio = [
  {version = "^2.22.4", markers = "platform_system != 'Linux'"}
]
pillow = "^10.0.1"
pylint = "^2.17.7"
pytest = "^7.4.2"
pytest-cov = "^4.1.0"

[tool.poetry.scripts]
xitomatl = "xitomatl.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.main]
ignore-paths = [
    "^tests/",
]
jobs=0

[tool.pylint."messages control"]
disable = [
    "broad-exception-caught",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-name-in-module",
    "redefined-outer-name",
    "too-few-public-methods",
    "too-many-instance-attributes",
    "too-many-return-statements",
    "wrong-import-position",
]
