[tool.poetry]
name = "xitomatl"
version = "0.1.0"
description = "Simple pomodoro timer app residing in tray"
license = "GPL-2.0-or-later"
authors = ["Lukas Holecek <hluk@email.cz>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
PySide6-Essentials = "^6.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
black = "^23.1"
flake8 = "^6.0.0"
isort = "^5.12.0"
bandit = "^1.7.5"
Nuitka = "^1.4.8"
zstandard = "^0.20.0"
imageio = [
  {version = "^2.22.4", markers = "platform_system != 'Linux'"}
]
pillow = ">=9.0.0"

[tool.poetry.scripts]
xitomatl = "xitomatl.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
