[tool.poetry]
name = "xitomatl"
version = "0.1.0"
description = "Simple pomodoro timer app residing in tray"
license = "GPL-2.0-or-later"
authors = ["Lukas Holecek <hluk@email.cz>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
PySide6 = "^6.2.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.11b1"
flake8 = "^4.0.1"
isort = "^5.10.1"
bandit = "^1.7.1"
safety = "^1.10.3"

[tool.poetry.scripts]
xitomatl = "xitomatl.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
