[tool.poetry]
name = "xitomatl"
version = "0.1.0"
description = "Simple pomodoro timer app residing in tray"
license = "GPL-2.0-or-later"
authors = ["Lukas Holecek <hluk@email.cz>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
PySide6 = "^6.2.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.11b1"
flake8 = "^4.0.1"
isort = "^5.10.1"
bandit = "^1.7.1"
safety = "^1.10.3"
Nuitka = [
  # There are issues with Nuitka 0.6.18 on Windows. It raises FileNotFoundError
  # in subprocess.Popen but does not show the executable path.
  {version = "=0.6.17", markers = "platform_system == 'Windows'"},
  {version = "^0.6.18", markers = "platform_system != 'Windows'"}
]
zstandard = "^0.16.0"
imageio = [
  {version = "^2.11.1", markers = "platform_system == 'Windows'"}
]

[tool.poetry.scripts]
xitomatl = "xitomatl.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
