---
# yamllint disable rule:line-length
name: package

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - pyqt5
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.buildname }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

        python-version:
          - 3.9

        poetry-version:
          - 1.1.11

        include:
          - os: windows-latest
            buildname: Windows
            artifact-name: xitomatl for Windows
            artifact-file: xitomatl.exe
            nuitka-arguments: --windows-icon-from-ico=xitomatl.png

          - os: macos-latest
            buildname: macOS
            artifact-name: xitomatl for macOS
            artifact-file: xitomatl.bin
            nuitka-arguments: --macos-onefile-icon=xitomatl.png

          - os: ubuntu-latest
            buildname: Linux
            artifact-name: xitomatl for Linux
            artifact-file: xitomatl.bin
            nuitka-arguments: --linux-onefile-icon=xitomatl.png

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use Poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Restore Poetry cache
        uses: actions/cache@v2
        id: cache-poetry
        with:
          path: ${{ runner.workspace }}/venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}-${{ steps.setup-python.outputs.python-version }}

      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_PATH: ${{ runner.workspace }}/venv
        run: poetry install --no-root --no-interaction

      - name: (Linux) Install runtime dependencies
        if: runner.os == 'Linux'
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          command: >-
            sudo apt-get update &&
            sudo apt-get install
            libegl1
            libopengl0

      - name: Create package
        env:
          POETRY_VIRTUALENVS_PATH: ${{ runner.workspace }}/venv
        run: >-
          poetry run nuitka3
          --onefile
          --standalone
          --python-flag=no_site
          --assume-yes-for-downloads
          --plugin-enable=pyqt5
          --show-modules
          --show-scons
          ${{ matrix.nuitka-arguments }}
          xitomatl

      - name: List package files
        shell: bash
        run: ls -lSh xitomatl.dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-file }}

      - name: Run smoke test
        shell: bash
        run: ./${{ matrix.artifact-file }} --version

      - name: Run tests
        env:
          POETRY_VIRTUALENVS_PATH: ${{ runner.workspace }}/venv
        run: poetry run pytest
